Hw06 pipeline execution
PrusovaIU/otus_golang_homework pull request #9
Opened 2024-05-21 13:55 UTC by PrusovaIU

## Домашнее задание №6 «Пайплайн»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - pipeline.go ~55 строк

### Критерии оценки
- [ ] CI-пайплайн зелёный - 5 баллов
- [ ] Добавлены новые юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2024-05-21 14:41 UTC, hungry-honeybadger requested changes

2024-05-21 14:41 UTC, vladislavmass commented on hw06_pipeline_execution/pipeline.go
> +			case out <- i:
Данный прочитаны, но их надо отправить следующему по цепочке

2024-05-21 15:11 UTC, PrusovaIU commented on hw06_pipeline_execution/pipeline.go
> +			case out <- i:
done  нужно отправить следующему?

2024-05-21 18:46 UTC, vladislavmass commented on hw06_pipeline_execution/pipeline.go
> +			case out <- i:
Прошлый раз не все отправилось. данная реализация выйдет по done только в случае если кто то после отправки done запишит данные в канал stageOut, если же записи не будет то наш код просто зависинет на ожидание этой записи

2024-05-22 19:41 UTC, vladislavmass requested changes

2024-05-22 19:41 UTC, vladislavmass commented on hw06_pipeline_execution/pipeline.go
> +		defer close(stageDone)
Зачем пораждать сигнал, которого нет изначально? Предположим ситуация  у нас есть пайплайн из 20 стейджей. На вход мы подали 3 значения и закрыли канал, первый стейдж обработал  эти 3 значения и закрыл канал. После этого наш `stageWrapper` вышел из цикла range for chanel так как канал закрыт и по логике кода отправил следующему `stageWrapper` сигнал done и таким образом получается что done инициировал не вызывающий код а ``stageWrapper`` и это является некорректным поведением

2025-03-03 19:50 UTC, vladislavmass approved these changes

2025-03-03 19:50 UTC, vladislavmass commented on hw06_pipeline_execution/pipeline.go
> +				for !result {
Поясните зачем нужен этот цикл for. Ведь если у нас сработает отправки в канал chIn то мы выйдем через изменение result на true. Если работал done, то мы выйдем через return и получается что этот цикл никогда не выполнится более 1 раза

2025-03-13 16:57 UTC, merged